### ISSUE TITLE
skin rarity issue

### ISSUE THREAD

**Issue by xevss** [B3akers/csgo-fake-opening#4]
skin rarity messes up and makes normal skins appear as reds etc , example image attached
![image](https://user-images.githubusercontent.com/79365332/108596641-5d9dc580-7354-11eb-937f-5f5aefa95f32.png)

**Comment by Ebzdyberybencjusz** [comment]
same issue, only red items drop ;/

**Comment by willn1337** [comment]
i think it's only dropping reds because econ_paint_kit_definition::get_rarity_value() is only returning 32, so the if statement at line 129 in csgo_sdk.cpp is always passing and the rarity value gets set to 6, dunno how to fix though

**Comment by B3akers** [comment]
fixed
